# Permalinks
permalink:                              /:categories/:title/
relative_permalinks:                    true

# Setup
title:                                  kempkens.io
tagline:                                Anwendungsentwickler
url:                                    https://kempkens.io
baseurl:                                /

include:                                [".htaccess"]
exclude:                                ["tmp", "Gemfile", "Gemfile.lock", "Makefile"]
