baseURL = "https://kempkens.io"
title = "Daniel Kempkens"
defaultContentLanguage = "de"
languageCode = "de-de"
theme = "hello-friend-ng"

enableRobotsTXT = true
disableKinds = ["taxonomy", "term", "RSS"]

[params]
homeSubtitle = "Anwendungsentwickler"

disableReadOtherPosts = true
enableSharingButtons = false
enableGlobalLanguageMenu = false

[params.logo]
logoMark = "$"
logoText = "cd /home/"
logoHomeLink = "/"
logoCursorColor = "#ffa86a"

[[params.social]]
name = "gitea"
url = "https://git.kempkens.io/daniel"
rel = "me"

[[params.social]]
name = "github"
url = "https://github.com/nifoc"
rel = "me"

[[params.social]]
name = "keyoxide"
url = "https://keyoxide.org/028BCE9BABB5145AAAA1FB8410BE1D47E5ADFF92"
rel = "me"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/danielkempkens/"
rel = "me"

[[params.social]]
name = "ycombinator"
url = "https://news.ycombinator.com/user?id=nifoc"
rel = "me"

[[params.social]]
name = "mastodon"
url = "https://networked.systems/@daniel"
rel = "me"

[[params.social]]
name = "matrix"
url = "https://matrix.to/#/@daniel:kempkens.io"
rel = "me"

[menu]
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "https://blog.kempkens.io"
