baseURL = "https://kempkens.io"
title = "Daniel Kempkens"
defaultContentLanguage = "de"
languageCode = "de-de"
theme = "hello-friend-ng"

enableRobotsTXT = true
disableKinds = ["taxonomy", "term", "RSS"]

[params]
homeSubtitle = "Anwendungsentwickler"

disableReadOtherPosts = true
enableSharingButtons = false
enableGlobalLanguageMenu = false

[params.logo]
logoMark = "$"
logoText = "cd /home/"
logoHomeLink = "/"
logoCursorColor = "#ffa86a"

[[params.social]]
name = "github"
url = "https://github.com/nifoc"

[[params.social]]
name = "keybase"
url = "https://keybase.io/nifoc"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/danielkempkens/"

[[params.social]]
name = "ycombinator"
url = "https://news.ycombinator.com/user?id=nifoc"

[[params.social]]
name = "mastodon"
url = "https://mastodon.kempkens.io/@daniel"

[[params.social]]
name = "matrix"
url = "https://matrix.to/#/@daniel:kempkens.io"

[menu]
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "https://blog.kempkens.io"
